---
  - name: init_skript
    hosts: localhost
    become: true
    vars_files:
      - users.yaml
    pre_tasks:
      - name: update cache
        pacman:
          update_cache: true
    tasks:
      - name: ensure users exist
        user:
          name: "{{ item.name }}"
          password: "{{ item.password }}"
          shell: /bin/bash
          create_home: true
        loop: "{{ users }}" 
        #no_log: true
