---
  - name: Init_skript
    hosts: localhost
    become: true
    gather_facts: false

    vars_files:
      - users.yaml

    pre_tasks:
      - name: Install reflector
        pacman:
          name: reflector
          state: present

      - name: Optimize pacman mirror list
        command: >
          reflector --country Germany --age 12 --protocol https --sort rate
          --save /etc/pacman.d/mirrorlist

      - name: Update cache
        pacman:
          update_cache: true

    tasks:
      - name: Install base utilities
        pacman:
          name:
            - fish
            - sudo
            - wget
            - curl
            - man-db
            - man-pages
            - unzip
            - less
            - which
            - pacman-contrib
          state: present

      - name: Ensure users exist
        user:
          name: "{{ item.name }}"
          password: "{{ item.password }}"
          shell: /bin/fish
          groups: "{{ item.groups | default([]) }}"
          append: true
          create_home: true
        loop: "{{ users }}" 
        no_log: true

      - name: Allow wheel group to use sudo
        lineinfile:
          path: /etc/sudoers
          regexp: '^# %wheel ALL=\(ALL:ALL\) ALL'
          line: '%wheel ALL=(ALL:ALL) ALL'
          validate: 'visudo -cf %s'

      - name: Detect VGA controllers
        shell: lspci | grep -i 'vga'
        register: vga_output

      - name: Show detected GPU (debug)
        debug:
          msg: "{{ vga_output.stdout }}"

      - name: Install Intel GPU driver
        pacman:
          name: xf86-video-intel
          state: present
        when: '"Intel" in vga_output.stdout'

      - name: Install AMD GPU driver
        pacman:
          name: xf86-video-amdgpu
          state: present
        when: '"Radeon" in vga_output.stdout or "AMD" in vga_output.stdout'

      - name: Install NVIDIA GPU driver
        pacman:
          name:
            - nvidia
            - nvidia-utils
          state: present
        when: '"NVIDIA" in vga_output.stdout'

      - name: Install Mesa and Vulkan drivers
        pacman:
          name:
            - mesa
            - vulkan-intel
            - vulkan-radeon
            - libva-mesa-driver
            - libvdpau
          state: present
