---
  - name: init_skript
    hosts: localhost
    become: true
    pre_tasks:
      - name: update cache
        pacman:
          update_cache: true
    tasks:
      - name: install fish
        pacman: name=fish
